Refosus.Web/Controllers/TracingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Refosus.Web.Controllers
{
    [Authorize(Roles = "crmAdministrator")]
    public class TracingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

Refosus.Web/Views/Tracings/Create.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tracings">Seguimientos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crear seguimiento</li>
        </ol>
    </nav>
    <a asp-controller="Tracings" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2" >
        <input type="hidden" id="user" value="@User.Identity.Name" />
        <div class="card-header" >
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Crear un nuevo seguimineto</h3></center>
        </div>
        <div class="card-body" >
            <input type="hidden" id="user" value="@User.Identity.Name" />
            <form id="tracingsForm" >
                <div class="row" >
                    <div class="col-md-6" >
                        <label>Contacto</label>
                        <select id="listContacts" class="form-control" required>
                            <option value="" >-- Contacto --</option>
                        </select>
                    </div>
                    <div class="col-md-6" >
                        <label>Tipo de observacion</label>
                        <select id="listTypesObservations" class="form-control" required>
                            <option value="" >-- tipo de observacion --</option>
                        </select>
                    </div>
                    <div style="display:none" class="col-md-4" >
                        <label>Canal</label>
                        <select id="listChannels" class="form-control">
                            <option value="" >-- Canal --</option>
                        </select>
                    </div>
                </div>
                <div class="row mt-3" >
                    <div class="col-md-12" >
                        <label>Observación</label>
                        <textarea id="observation" class="form-control" required></textarea>
                    </div>
                </div>
                <hr />
                <div class="form-check">
                    <input class="form-check-input" value="0" type="checkbox" id="quotation">
                    <strong>
                        <label class="form-check-label" for="flexCheckDefault">
                            Cotizar
                        </label>
                    </strong>
                </div>
                <hr />
                <div id="quotationContent" class="row" hidden>
                    <div class="col-md-4">
                        <label>Valor cotizado</label>
                        <input id="price" type="number" class="form-control"  />
                    </div>
                </div>
                <hr />
                <button class="btn btn-outline-success" >Registrar</button>
            </form>
            <button id="moreTask" class="btn btn-outline-primary float-right" >Añadir tarea</button>
        </div>
    </div>
    <div id="listTask">
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Ext.js"></script>
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/Tracings.js"></script>
}

Refosus.Web/Views/Tracings/Details.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tracings">Seguimientos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detalles</li>
        </ol>
    </nav>
    <a asp-controller="Tracings" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Detalles</h3></center>
        </div>
        <div class="card-body">
            <input type="hidden" id="detailsId" key="@ViewBag.Id" />
            <div class="row">
                <div class="col-md-6">
                    <label>Contacto</label>
                    <input id="contactDetails" type="text" class="form-control" readonly />
                </div>
                <div class="col-md-6">
                    <label>Tipo de observacion</label>
                    <input id="typeObservationDetails" type="text" class="form-control" readonly />
                </div>
                <div style="display:none" class="col-md-4">
                    <label>Canal</label>
                    <input id="typeChannelDetails" type="text" class="form-control" readonly />
                </div>
            </div>
            <div class="row mt-3" >
                <div class="col-md-3">
                    <label>Valor cotizado</label>
                    <input id="quotationDetails" type="text" class="form-control" readonly />
                </div>
                <div class="col-md-3">
                    <label>Fecha valor cotizado</label>
                    <input id="quotationDateDetails" type="text" class="form-control"  readonly />
                </div>
                <div class="col-md-3">
                    <label>Valor de venta</label>
                    <input id="valueDetails" type="text" class="form-control" readonly />
                </div>
                <div class="col-md-3">
                    <label>Fecha valor venta</label>
                    <input id="valueDateDetails" type="text" class="form-control" readonly />
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6" >
                    <label>Fecha de creación</label>
                    <input id="createdDetails" type="text" class="form-control" readonly />
                </div>
                <div class="col-md-6">
                    <label>Fecha de ultima actualización</label>
                    <input id="updatedDetails" type="text" class="form-control" readonly />
                </div>
            </div>
            <div class="row mt-3" >
                <div class="col-md-12" >
                    <label>Observación</label>
                    <textarea id="observationDetails" class="form-control" readonly></textarea>
                </div>
            </div>
        </div>
    </div>
    <div  class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Tareas</h3></center>
        </div>
        <div  class="card-body">
            <div id="tasks">
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Ext.js"></script>
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/Tracings.js"></script>
}

Refosus.Web/Views/Tracings/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tracings">Seguimientos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
    </nav>
    <a asp-controller="Tracings" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <input type="hidden" id="user" value="@User.Identity.Name" />
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Editar</h3></center>
        </div>
        <div class="card-body">
            <input type="hidden" id="editId" key="@ViewBag.Id" />
            <div class="row">
                <div class="col-md-6">
                    <label>Contacto</label>
                    <select id="contactEdit" class="form-control" readonly disabled></select>
                </div>
                <div class="col-md-6">
                    <label>Tipo de observacion</label>
                    <select id="typeObservationEdit" class="form-control"></select>
                </div>
                <div style="display:none" class="col-md-4">
                    <label>Canal</label>
                    <select id="typeChannelEdit" class="form-control" required></select>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-2 ml-5">
                    <strong>
                        <label>Cotizar</label>
                    </strong>
                    <div class="form-check ml-3">
                        <input class="form-check-input" value="0" type="checkbox" id="quotationEdit">
                    </div>
                </div>
                <div class="col-md-3">
                    <label>Valor cotizado</label>
                    <input id="priceEdit" type="number" class="form-control" readonly/>
                </div>
                <div class="col-md-2 ml-5">
                    <strong>
                        <label>Venta</label>
                    </strong>
                    <div class="form-check ml-3">
                        <input class="form-check-input" value="0" type="checkbox" id="saleEdit">
                    </div>
                </div>
                <div class="col-md-3">
                    <label>Valor de venta</label>
                    <input id="valueEdit" type="number" class="form-control" readonly />
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6" >
                    <label>Fecha de creación</label>
                    <input id="createdEdit" type="text" class="form-control" readonly />
                </div>
                <div class="col-md-6">
                    <label>Fecha de ultima actualización</label>
                    <input id="updatedEdit" type="text" class="form-control" readonly />
                </div>
            </div>
            <div class="row mt-3" >
                <div class="col-md-12" >
                    <label>Observación</label>
                    <textarea id="observationEdit" class="form-control"></textarea>
                </div>
            </div>
            <hr />
            <button id="updateTracing" class="btn btn-outline-success">Editar</button>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/Tracings.js"></script>
}

Refosus.Web/Views/Tracings/Index.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item active" aria-current="page">Seguimientos</li>
        </ol>
    </nav>
    <a asp-controller="Tracings" asp-action="Create" class="btn btn-outline-info" role="button">Agregar nuevo seguimiento</a>
    <a asp-controller="TypesObservations" asp-action="Index" class="btn btn-outline-info" role="button">Tipos de observaciones</a>
    <a asp-controller="Tasks" asp-action="Index" class="btn btn-outline-info" role="button">Tareas</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Seguimientos</h3></center>
        </div>
        <div class="card-body table-responsive">
            <span id="loading" ></span>
            <table id="tableTracings" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Contacto</th>
                        <th>Tipo de observacion</th>
                        <th>Observacion</th>
                        <th>Fecha</th>
                        <th>Detalles</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                <tbody id="tracings">
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/Tracings.js"></script>
}