Refosus.Web/Controllers/TypesCasesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Refosus.Web.Data.Entities;
using Refosus.Web.Data;

namespace Refosus.Web.Controllers
{
    public class TypesCasesController : Controller
    {

        private DataContext ctx;

        public TypesCasesController(DataContext dataContext)
        {
            this.ctx = dataContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [BindProperty]
        public TypeCaseEntity typeCaseEntity { get; set; }
        public IActionResult Store()
        {
            typeCaseEntity.Status = 1;
            typeCaseEntity.CreateAt = DateTime.Now.ToUniversalTime();
            ctx.Add(typeCaseEntity);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            return View();
        }

        public IActionResult Update(int id)
        {
            return null;
        }

        public IActionResult Delete(int id)
        {
            return null;
        }
    }
}

Refosus.Web/Views/TypesCases/Create.cshtml
@model Refosus.Web.Models.TypeCase;
@{
    ViewData["Title"] = "TIPOS DE CASOS";
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<br />
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a asp-controller="Cases" asp-action="Index">Casos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar nuevo tipo de caso</li>
        </ol>
    </nav>
    <a asp-controller="Cases" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <center><h3>Agregar nuevo tipo de caso</h3></center>
        </div>
        <div class="card-body">
            <form asp-controller="TypesCases" asp-action="Store" method="post">
                <div class="row">
                    <div class="col-md-6">
                        <label>Tipo de caso</label>
                        <input asp-for="Case" class="form-control" type="text" required />
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-outline-success mt-4">Registrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Refosus.Web/Views/TypesCases/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}