Refosus.Web/Controllers/CasesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Refosus.Web.Data;
using Refosus.Web.Data.Entities;
using Refosus.Web.Models;
using System.IO;
using Microsoft.EntityFrameworkCore;
using FluentDateTime;
using Refosus.Web.Helpers;

namespace Refosus.Web.Controllers
{
    public class CasesController : Controller
    {
        DataContext ctx;
        ICaseTrait helper;
        
        public CasesController(DataContext _context, ICaseTrait _helper)
        {
            ctx = _context;
            helper = _helper;
        }

        [Authorize(Roles = "maintenanceCreatorAdministrator, maintenanceAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Index(string? message)
        {
            ViewBag.message = message;
            List<CaseEntity> facade;
            if (User.IsInRole("maintenanceFilterAdministrator"))
            {
                facade = ctx.CaseEntity.Where(x => x.Status == 1 || x.Status == 2 || x.Status == 3).OrderBy(x => x.CreatedAt).ToList();
            }
            else
            {
                facade = ctx.CaseEntity.Where(x => x.Status == 1 || x.Status == 2 || x.Status == 3).Where(x => x.Sender == User.Identity.Name || x.Responsable == User.Identity.Name).OrderBy(x => x.CreatedAt).ToList();
            }

            return View(facade);
        }

        [Authorize(Roles = "maintenanceAdministrator, maintenanceCreatorAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Create()
        {
            ViewBag.typesCases = ctx.TypeCaseEntity.ToList();
            ViewBag.businessUnits = ctx.BusinessUnitEntity.ToList();
            ViewBag.usersList = ctx.Users.ToList();
            return View();
        }

        [BindProperty]
        public CaseEntity caseEntity { get; set; }
        [Authorize(Roles = "maintenanceCreatorAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Store()
        {
            caseEntity.Responsable = (String.IsNullOrEmpty(caseEntity.Responsable)) ? "yecidr@refocosta.com" : caseEntity.Responsable;
            caseEntity.Sender = (String.IsNullOrEmpty(caseEntity.Sender)) ? User.Identity.Name : caseEntity.Sender;
            caseEntity.Status = 1;
            caseEntity.Code = helper.Random();
            caseEntity.Solution = "Este caso aún no tiene respuesta";
            caseEntity.CreatedAt = System.DateTime.Now.ToUniversalTime();
            caseEntity.DeadLine = (caseEntity.DeadLine == DateTime.MinValue) ? DateTime.Now.AddBusinessDays(1) : caseEntity.DeadLine;
            ctx.Add(caseEntity);
            ctx.SaveChanges();
            var dependencies = new List<dynamic>();
            dependencies.Add(new
            {
                CaseId = ctx.CaseEntity.Max(item => item.Id),
                CaseCode = caseEntity.Code,
                CaseDeadline = caseEntity.DeadLine,
                CaseIssue = caseEntity.Issue,
                CaseDescription = caseEntity.Description

            });
            string[] sender = new string[1];
            sender[0] = caseEntity.Sender;
            string[] responsable = new string[1];
            responsable[0] = caseEntity.Responsable;
            helper.MailTypeStore(sender, dependencies, 1);
            helper.MailTypeStore(responsable, dependencies, 2);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "maintenanceAdministrator, maintenanceCreatorAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Details(int id)
        {
            CaseEntity details = ctx.CaseEntity.Where(x => x.Id == id).Where(x => x.Status == 1 || x.Status == 2 || x.Status == 3).Include(t => t.TypesCases).Include(t => t.BusinessUnits).FirstOrDefault();
            if (details == null)
            {
                return RedirectToAction("Index");
            }
            return View(details);
        }

        [Authorize(Roles = "maintenanceCreatorAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Edit(int id)
        {
            CaseEntity edit = ctx.CaseEntity.Where(x => x.Id == id).Where(x => x.Status == 1 || x.Status == 2 || x.Status == 3).Include(t => t.TypesCases).Include(t => t.BusinessUnits).FirstOrDefault();
            if (edit == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.typesCases = ctx.TypeCaseEntity.ToList();
            ViewBag.businessUnits = ctx.BusinessUnitEntity.ToList();
            ViewBag.usersList = ctx.Users.ToList();
            return View(edit);
        }

        [BindProperty]
        public CaseEntity caseEntityUpdate { get; set; }
        [Authorize(Roles = "maintenanceCreatorAdministrator, maintenanceFilterAdministrator")]
        public IActionResult Update()
        {
            CaseEntity update = ctx.CaseEntity.Find(caseEntityUpdate.Id);
            if (update != null)
            {
                update.Issue = caseEntityUpdate.Issue;
                update.Description = caseEntityUpdate.Description;
                update.Sender = (!String.IsNullOrEmpty(update.Sender)) ? update.Sender : User.Identity.Name;
                update.TypesCasesId = caseEntityUpdate.TypesCasesId;
                update.Priority = caseEntityUpdate.Priority;
                update.Responsable = caseEntityUpdate.Responsable;
                update.BusinessUnitsId = caseEntityUpdate.BusinessUnitsId;
                update.Ubication = caseEntityUpdate.Ubication;
                update.Solution = caseEntityUpdate.Solution;
                update.DeadLine = caseEntityUpdate.DeadLine;
                ctx.SaveChanges();
                var dependencies = new List<dynamic>();
                dependencies.Add(new
                {
                    CaseId = update.Id,
                    CaseCode = update.Code,
                    CaseDeadline = update.DeadLine,
                    CaseResponsable = update.Responsable,
                    CaseIssue = update.Issue,
                });
                string[] sender = new string[1];
                sender[0] = update.Sender;
                string[] responsable = new string[1];
                responsable[0] = update.Responsable;
                helper.MailTypeUpdate(sender, dependencies, 1);
                helper.MailTypeUpdate(responsable, dependencies, 2);
            }
            return RedirectToAction("Edit", new { id = caseEntityUpdate.Id });
        }

        [Authorize(Roles = "maintenanceAdministrator")]
        public IActionResult Solution(int id)
        {
            CaseEntity solution = ctx.CaseEntity.Where(x => x.Id == id).Where(x => x.Status == 1 || x.Status == 3).FirstOrDefault();
            if (solution == null)
            {
                return RedirectToAction("Index");
            }
            return View(solution);
        }

        [BindProperty]
        public CaseEntity caseEntitySolution { get; set; }
        [Authorize(Roles = "maintenanceAdministrator")]
        public IActionResult StoreSolution()
        {
            CaseEntity update = ctx.CaseEntity.Find(caseEntitySolution.Id);
            
            if (update != null)
            {
                update.Solution = caseEntitySolution.Solution;
                update.Hours = caseEntitySolution.Hours;
                update.ClosingDate = System.DateTime.Now.ToUniversalTime();
                update.Status = 2;
                ctx.SaveChanges();
                var dependencies = new List<dynamic>();
                dependencies.Add(new
                {
                    CaseId = update.Id,
                    CaseCode = update.Code,
                    CaseDeadline = update.DeadLine,
                    CaseResponsable = update.Responsable,
                    CaseClosingDate = update.ClosingDate,
                    CaseIssue = update.Issue
                });
                string[] sender = new string[1];
                sender[0] = update.Sender;
                string[] responsable = new string[1];
                responsable[0] = update.Responsable;
                helper.mailTypeSolution(sender, dependencies, 1);
                helper.mailTypeSolution(responsable, dependencies, 2);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "maintenanceFilterAdministrator")]
        public IActionResult Delete(int id)
        {
            var delete = ctx.CaseEntity.Find(id);
            if (delete == null)
            {
                return RedirectToAction("Index");
            }
            delete.Status = 0;
            ctx.SaveChanges();
            var dependencies = new List<dynamic>();
            dependencies.Add(new
            {
                CaseId = delete.Id,
                CaseCode = delete.Code,
                CaseDeadline = delete.DeadLine,
                CaseResponsable = delete.Responsable,
            });
            string[] sender = new string[1];
            sender[0] = delete.Sender;
            string[] responsable = new string[1];
            responsable[0] = delete.Responsable;
            helper.mailTypeDelete(sender, dependencies, 1);
            helper.mailTypeDelete(responsable, dependencies, 2);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "maintenanceFilterAdministrator")]
        public IActionResult Thrash()
        {
            var thrash = ctx.CaseEntity.Where(x => x.Status == 0).ToList();
            return View(thrash);
        }

        [Authorize(Roles = "maintenanceFilterAdministrator")]
        public IActionResult Enable(int id)
        {
            var enable = ctx.CaseEntity.Find(id);
            if (enable == null)
            {
                return RedirectToAction("Index");
            }
            enable.Status = 1;
            ctx.SaveChanges();

Refosus.Web/Views/Cases/Create.cshtml
@model Refosus.Web.Models.Case
@{
    ViewData["Title"] = "CASOS";
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<br />
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a asp-controller="Cases" asp-action="Index">Casos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar nuevo caso</li>
        </ol>
    </nav>
    <a asp-controller="Cases" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <center><h3>Agregar nuevo caso</h3></center>
        </div>
        <div class="card-body">
            @if (User.IsInRole("maintenanceCreatorAdministrator"))
            {
                <form asp-controller="Cases" asp-action="Store" method="post">
                    <label>Tema del caso</label>
                    <input asp-for="Issue" class="form-control" type="text" required />
                    <label>Descripcion del caso</label>
                    <textarea asp-for="Description" class="form-control" required></textarea>
                    <input type="hidden" asp-for="TypesCasesId" value="1" />
                    <input type="hidden" asp-for="BusinessUnitsId" value="1" />
                    <hr />
                    <button class="btn btn-outline-success">Registrar</button>
                </form>
            }
            else
            {
                <form asp-controller="Cases" asp-action="Store" method="post">
                    <label>Tema del caso</label>
                    <input asp-for="Issue" class="form-control" type="text" required />
                    <label>Descripcion del caso</label>
                    <textarea asp-for="Description" class="form-control" required></textarea>
                    <div class="row">
                        <div class="col-md-3">
                            <label>Remitente</label>
                            <select asp-for="Sender" class="form-control">
                                <option value="">-- REMITENTE --</option>
                                @foreach (var item in ViewBag.usersList)
                                {
                                    <option value="@item.Email">@item.FullName</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label>Tipo de caso</label>
                            <select asp-for="TypesCasesId" class="form-control" required>
                                <option value="">-- TIPO DE CASO --</option>
                                @foreach (var item in ViewBag.typesCases)
                                {
                                    <option value="@item.Id">@item.Case</option>
                                }

                            </select>
                        </div>
                        <div class="col-md-3">
                            <label>Unidad de negocio</label>
                            <select asp-for="BusinessUnitsId" class="form-control" required>
                                <option value="">-- UNIDAD DE NEGOCIO --</option>
                                @foreach (var item in ViewBag.businessUnits)
                                {
                                    <option value="@item.Id">@item.Business</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label>Ubicacion</label>
                            <input asp-for="Ubication" class="form-control" type="text" required />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label>Prioridad</label>
                            <select asp-for="Priority" class="form-control" required>
                                <option value="">-- PRIORIDAD --</option>
                                <option value="1">Urgente</option>
                                <option value="2">Alta</option>
                                <option value="3">Normal</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label>Responsable</label>
                            <select asp-for="Responsable" class="form-control" required>
                                <option value="">-- RESPONSABLE --</option>
                                @foreach (var item in ViewBag.usersList)
                                {
                                    <option value="@item.Email">@item.FullName</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label>Fecha limite</label>
                            <input asp-for="DeadLine" class="form-control" type="datetime-local" required />
                        </div>
                    </div>
                    <hr />
                    <button class="btn btn-outline-success">Registrar</button>
                </form>
            }
        </div>
    </div>
    <br />
</div>

Refosus.Web/Views/Cases/Details.cshtml
@model Refosus.Web.Data.Entities.CaseEntity
@{
    ViewData["Title"] = "CASOS";
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<br />
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a asp-controller="Cases" asp-action="Index">Casos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detalles</li>
        </ol>
    </nav>
    <a asp-controller="Cases" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <center><h3>Detalles</h3></center>
        </div>
        <div class="card-body">
            <label>Tema</label>
            <input readonly asp-for="Issue" class="form-control" type="text" />
            <label>Descripcion</label>
            <textarea class="form-control" asp-for="Description" readonly ></textarea>
            <div class="row" >
                <div class="col-md-3">
                    <label>Remitente</label>
                    <input readonly asp-for="Sender" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Codigo</label>
                    <input readonly asp-for="Code" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Prioridad</label>
                    @if (Model.Priority == 1)
                    {
                        <input readonly value="Urgente" class="form-control" type="text" />
                    }
                    else if (Model.Priority == 2)
                    {
                        <input readonly value="Alto" class="form-control" type="text" />
                    }
                    else
                    {
                        <input readonly value="Normal" class="form-control" type="text" />
                    }
                </div>
                <div class="col-md-3">
                    <label>Responsable</label>
                    <input readonly asp-for="Responsable" class="form-control" type="text" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Tipo de caso</label>
                    <input readonly asp-for="TypesCases.Case" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Cumplimiento</label>
                    @if (Model.Fulfillment == 1 || Model.Fulfillment == 0)
                    {
                        <input readonly value="Sin cambios" class="form-control" type="text" />
                    }
                    else if (Model.Fulfillment == 2)
                    {
                        <input readonly value="Llamado de atencion" class="form-control" type="text" />
                    }
                </div>
                <div class="col-md-3">
                    <label>Unidad de negocio</label>
                    <input readonly asp-for="BusinessUnits.Business" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Ubicacion</label>
                    <input readonly asp-for="Ubication" class="form-control" type="text" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Minutos utilizados</label>
                    <input readonly asp-for="Hours" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Fecha limite</label>
                    <input readonly asp-for="DeadLine" class="form-control" type="text" />
                </div>
                    <div class="col-md-3">
                    <label>Fecha de cerrado</label>
                    <input readonly asp-for="ClosingDate" class="form-control" type="text" />
                </div>
                <div class="col-md-3">
                    <label>Fecha de creacion</label>
                    <input readonly asp-for="CreatedAt" class="form-control" type="text" />
                </div>
            </div>
            <label>Solucion</label>
            <textarea class="form-control" asp-for="Solution" readonly></textarea>
        </div>
    </div>
</div>

Refosus.Web/Views/Cases/Edit.cshtml
@model Refosus.Web.Data.Entities.CaseEntity
@{
    ViewData["Title"] = "CASOS";
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<br />
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a asp-controller="Cases" asp-action="Index">Casos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
    </nav>
    <a asp-controller="Cases" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <center><h3>Editar caso</h3></center>
        </div>
        <div class="card-body">
            <form asp-controller="Cases" asp-action="Update" method="post">
                <input asp-for="Id" type="hidden" />
                <label>Tema del caso</label>
                <input asp-for="Issue" class="form-control" type="text" required />
                <label>Descripcion del caso</label>
                <textarea asp-for="Description" class="form-control" required></textarea>
                <div class="row">
                    <div class="col-md-4">
                        <label>Tipo de caso</label>
                        <select asp-for="TypesCasesId" class="form-control" required>
                            <option value="">-- TIPO DE CASO --</option>
                            @foreach (var item in ViewBag.typesCases)
                            {
                                <option value="@item.Id">@item.Case</option>
                            }

                        </select>
                    </div>
                    <div class="col-md-4">
                        <label>Unidad de negocio</label>
                        <select asp-for="BusinessUnitsId" class="form-control" required>
                            <option value="">-- UNIDAD DE NEGOCIO --</option>
                            @foreach (var item in ViewBag.businessUnits)
                            {
                                <option value="@item.Id">@item.Business</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label>Ubicacion</label>
                        <input asp-for="Ubication" class="form-control" type="text" required />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label>Prioridad</label>
                        <select asp-for="Priority" class="form-control" required>
                            <option value="">-- PRIORIDAD --</option>
                            <option value="1">Urgente</option>
                            <option value="2">Alta</option>
                            <option value="3">Normal</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label>Responsable</label>
                        <select asp-for="Responsable" class="form-control" required>
                            <option value="">-- RESPONSABLE --</option>
                            @foreach (var item in ViewBag.usersList)
                            {
                                <option value="@item.Email">@item.FullName</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label>Fecha limite</label>
                        <input asp-for="DeadLine" class="form-control" type="date" required />
                    </div>

                </div>
                <label>Diagnostigo inicial</label>
                <textarea asp-for="Solution" class="form-control"></textarea>
                <hr />
                <button class="btn btn-outline-success">Editar caso</button>
            </form>
        </div>
    </div>
</div>

Refosus.Web/Views/Cases/Index.cshtml
@model IEnumerable<Refosus.Web.Data.Entities.CaseEntity>
@{
    ViewData["Title"] = "CASOS";
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<br />
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item active" aria-current="page">Casos y mantenimiento</li>
        </ol>
    </nav>
    @if (User.IsInRole("maintenanceFilterAdministrator"))
    {
        <a asp-controller="Cases" asp-action="Create" class="btn btn-outline-info" role="button">Agregar nuevo caso</a>
        <a asp-controller="TypesCases" asp-action="Create" class="btn btn-outline-info" role="button">Agregar un tipo de caso</a>
        <a asp-controller="BusinessUnits" asp-action="Create" class="btn btn-outline-info" role="button">Agregar una unidad de negocio</a>
        <a asp-controller="Cases" asp-action="Thrash" class="btn btn-outline-warning" role="button">Papelera</a>
    }
    else if (User.IsInRole("maintenanceCreatorAdministrator"))
    {
        <a asp-controller="Cases" asp-action="Create" class="btn btn-outline-info" role="button">Agregar nuevo caso</a>
    }
    @if (ViewBag.message != null)
    {
        <br />
        <div class="alert alert-info mt-3" role="alert">
            @ViewBag.message
        </div>
    }

    <div class="card mt-2">
        <div class="card-header">
            <center><h3>Casos registrados</h3></center>
        </div>
        <div class="card-body table-responsive">
            <table id="index" class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Tema</th>
                        <th>Codigo</th>
                        <th>Remitente</th>
                        <th>Responsable</th>
                        <th>Estado</th>
                        <th>Fecha limite</th>
                        @if (User.IsInRole("maintenanceFilterAdministrator"))
                        {
                            <th>Detalles</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        }
                        else if (User.IsInRole("maintenanceCreatorAdministrator"))
                        {
                            <th>Detalles</th>
                            <th>Llamado de atención</th>
                        }
                        else
                        {
                            <th>Detalles</th>
                            <th>Solucionar</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var g in Model)
                    {
                    <tr>
                        <td>@g.Id</td>
                        <td>@g.Issue</td>
                        <td>@g.Code</td>
                        <td>@g.Sender</td>
                        <td>@g.Responsable</td>
                        @if (g.Status == 1)
                        {
                            <td><span class="badge bg-info">Abierto</span></td>
                        }
                        else if (g.Status == 2)
                        {
                            <td><span class="badge bg-success">Cerrado</span></td>
                        }
                        else
                        {
                            <td><span class="badge bg-warning">Vencido</span></td>
                        }
                        <td>@g.DeadLine</td>
                        @if (User.IsInRole("maintenanceFilterAdministrator"))
                        {
                            <td><a asp-controller="Cases" asp-action="Details" asp-route-id="@g.Id"><span style="color:dimgrey"><i class="fas fa-eye fa-2x"></i></span></a></td>
                            <td><a asp-controller="Cases" asp-action="Edit" asp-route-id="@g.Id"><span style="color:lightskyblue"><i class="far fa-edit fa-2x"></i></span></a></td>
                            <td><a onclick="return confirm('¿Esta seguro?')" asp-controller="Cases" asp-action="Delete" asp-route-id="@g.Id"><span style="color:red"><i class="far fa-trash-alt fa-2x"></i></span></a></td>
                        }
                        else if (User.IsInRole("maintenanceCreatorAdministrator"))
                        {
                            <td><a asp-controller="Cases" asp-action="Details" asp-route-id="@g.Id"><span style="color:dimgrey"><i class="fas fa-eye fa-2x"></i></span></a></td>
                            @if (DateTime.Now > g.DeadLine)
                            {
                                <td><a asp-controller="Cases" asp-action="Atention" asp-route-id="@g.Id"><span style="color:cornflowerblue"><i class="fas fa-bell fa-2x"></i></span></a></td>
                            }
                            else
                            {
                                <td><span style="color: dimgrey "><i class="fas fa-bell fa-2x"></i></span></td>
                            }

                        }
                        else
                        {
                            <td><a asp-controller="Cases" asp-action="Details" asp-route-id="@g.Id"><span style="color:dimgrey"><i class="fas fa-eye fa-2x"></i></span></a></td>
                            @if (g.Status == 1 || g.Status == 3)
                            {

                                <td><a asp-controller="Cases" asp-action="Solution" asp-route-id="@g.Id"><span style="color:lawngreen"><i class="fas fa-check-circle fa-2x"></i></span></a></td>

                            }
                            else
                            {
                                <td><span style="color: dimgrey"><i class="fas fa-check-circle fa-2x"></i></span></td>

                            }

                        }
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#index').DataTable({
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "zeroRecords": "No se encontraron resultados",
                    "info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "infoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sSearch": "Buscar:",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "sProcessing": "Procesando...",
                }
            });
        });
    </script>
}