Refosus.Web/Controllers/TypesTasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Refosus.Web.Controllers
{
    [Authorize(Roles = "crmAdministrator")]
    public class TypesTasksController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

Refosus.Web/Views/TypesTasks/Create.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tasks">Tareas</a></li>
            <li class="breadcrumb-item"><a href="/TypesTasks">Tipos de tareas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crear tipo de tarea</li>
        </ol>
    </nav>
    <a asp-controller="TypesTasks" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Crear tipo de tarea</h3></center>
        </div>
        <div class="card-body">
            <form id="typesTasksForm">
                <div class="row">
                    <div class="col-md-6">
                        <label>Nombre</label>
                        <input id="name" class="form-control"  required />
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-outline-success ml-2 mt-4">Registrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/TypesTasks.js"></script>
}

Refosus.Web/Views/TypesTasks/Details.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tasks">Tareas</a></li>
            <li class="breadcrumb-item"><a href="/TypesTasks">Tipos de tareas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detalles</li>
        </ol>
    </nav>
    <a asp-controller="TypesTasks" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Detalles</h3></center>
        </div>
        <div class="card-body">
            <input type="hidden" id="detailsId" key="@ViewBag.Id" />
            <div class="row">
                <div class="col-md-4">
                    <label>Nombre</label>
                    <input id="nameDetails" class="form-control" readonly/>
                </div>
                <div class="col-md-4">
                    <label>Fecha de creación</label>
                    <input id="createdDetails" class="form-control" readonly/>
                </div>
                <div class="col-md-4">
                    <label>Fecha de ultima actualización</label>
                    <input id="updatedDetails" class="form-control" readonly/>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/TypesTasks.js"></script>
}

Refosus.Web/Views/TypesTasks/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tasks">Tareas</a></li>
            <li class="breadcrumb-item"><a href="/TypesTasks">Tipos de tareas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
    </nav>
    <a asp-controller="TypesTasks" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Editar</h3></center>
        </div>
        <div class="card-body">
            <input type="hidden" id="editId" key="@ViewBag.Id" />
            <div class="row">
                <div class="col-md-4">
                    <label>Nombre</label>
                    <input id="nameEdit" class="form-control" />
                </div>
                <div class="col-md-4">
                    <label>Fecha de creación</label>
                    <input id="createdEdit" class="form-control" readonly />
                </div>
                <div class="col-md-4">
                    <label>Fechal de ultima actualización</label>
                    <input id="updatedEdit" class="form-control" readonly />
                </div>
            </div>
            <hr />
            <button id="editTypesTasks" class="btn btn-outline-success" >Editar</button>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/TypesTasks.js"></script>
}

Refosus.Web/Views/TypesTasks/Index.cshtml
@{
    Layout = "~/Views/Shared/_Refosus1.cshtml";
}
<div class="container col-md-11">
    <br />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Home/Menu">Nativa</a></li>
            <li class="breadcrumb-item"><a href="/Tracings">Seguimientos</a></li>
            <li class="breadcrumb-item"><a href="/Tasks">Tareas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Tipos de tareas</li>
        </ol>
    </nav>
    <a asp-controller="Tasks" asp-action="Index" class="btn btn-outline-primary" role="button">Atras</a>
    <a asp-controller="TypesTasks" asp-action="Create" class="btn btn-outline-info" role="button">Añadir tipo de tarea</a>
    <div class="card mt-2">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-primary-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
            <center><h3>Tipos de tareas</h3></center>
        </div>
        <div class="card-body table-responsive">
            <table id="tableTypesTasks" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Fecha de creación</th>
                        <th>Detalles</th>
                        <th>Editar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody id="typesTaskList">
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Fetch.js"></script>
    <script src="~/js/TypesTasks.js"></script>
}